name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.10.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      run: mix test
    - name: Prepare release
      run: |
        export SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}
        mix compile
        npm install --prefix ./assets
        npm run deploy --prefix ./assets
        mix phx.digest
        mix release 
        export build_number=$(_build/prod/rel/learning_ec2_1/bin/learning_ec2_1 version | cut -d ' ' -f2)
        tar -czvf ${build_number}.tar.gz -C _build .
        echo "New build at ${build_number}"
      env:
        MIX_ENV: prod
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
    - name: Store build in s3
      run: s3 cp ${build_number}.tar.gz s3://learning-ec2-1-deployments